[build]
publish = "opt/build/repo"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# headers are available in _headers.$NODE_ENV files
# waiting for https://community.netlify.com/t/toml-different-headers-for-different-contexts/1159
