version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
workflows:
  version: 2
  commit:
    jobs:
      - build
  # monitoring_hourly:
  #   triggers:
  #     - schedule:
  #         cron: "0 * * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - monitoring
jobs:
  monitoring:
    docker:
      - image: "cimg/node:18.15-browsers"
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: install
          command: npm ci
      - run:
          name: monitor
          command: npm run monitoring
  build:
    docker:
      - image: "cimg/node:18.15-browsers"
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: install
          command: npm ci
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: integration
          command: |
            npm run integration:headless
            npm run integration:multi-window-test:headless
